openapi: "3.0.3"
info:
  title: "com_the_chance_cup_cake_media API"
  description: "com_the_chance_cup_cake_media API"
  version: "1.0.0"
servers:
- url: "https://com_the_chance_cup_cake_media"
paths:
  /job:
    post:
      description: ""
      parameters:
      - name: "jobTitleId"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "company"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "workType"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "jobLocation"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "jobType"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "jobDescription"
        in: "query"
        required: false
        schema:
          type: "string"
      - name: "jobSalary"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Job"
  /job/{id}:
    delete:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "202":
          description: "Accepted"
          content:
            '*/*':
              schema:
                type: "string"
    get:
      description: ""
      parameters:
      - name: "id"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Job"
  /jobTitle:
    post:
      description: "todo this end point is a temporary solution and should be removed\
        \ in the future"
      parameters:
      - name: "jobTitle"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/JobTitle"
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                type: "string"
  /jobTitles:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/JobTitle"
  /jobs:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/JobWithJobTitle"
  /post:
    post:
      description: ""
      parameters:
      - name: "content"
        in: "query"
        required: false
        schema:
          type: "string"
      responses:
        "201":
          description: "Created"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Post"
  /post/{postId}:
    get:
      description: ""
      parameters:
      - name: "postId"
        in: "path"
        required: true
        schema:
          type: "string"
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/Post"
  /posts:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "array"
                items:
                  $ref: "#/components/schemas/Post"
  /json/kotlinx-serialization:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "string"
components:
  schemas:
    Job:
      type: "object"
      properties:
        id:
          type: "string"
        jobTitleId:
          type: "integer"
          format: "int32"
        company:
          type: "string"
        createdAt:
          type: "integer"
          format: "int64"
        workType:
          type: "string"
        jobLocation:
          type: "string"
        jobType:
          type: "string"
        jobDescription:
          type: "string"
        jobSalary:
          type: "number"
          format: "double"
    JobTitle:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int32"
        title:
          type: "string"
    JobWithJobTitle:
      type: "object"
      properties:
        id:
          type: "string"
        jobTitle:
          $ref: "#/components/schemas/JobTitle"
        company:
          type: "string"
        createdAt:
          type: "integer"
          format: "int64"
        workType:
          type: "string"
        jobLocation:
          type: "string"
        jobType:
          type: "string"
        jobDescription:
          type: "string"
        jobSalary:
          type: "number"
          format: "double"
    Post:
      type: "object"
      properties:
        id:
          type: "string"
        content:
          type: "string"
        createdAt:
          type: "integer"
          format: "int64"